import "./globals.css";
import Header from "./components/Header";
import config from "../config";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";
import AppProvider from "@/redux/provider";
import MainLayout from "@/layouts/MainLayout";

export const metadata = {
  title: {
    default: config.appName,
    template: `%s || ${config.appName}`,
  },
  description: "Generated by create next app",
  keywords: "Best online shopping store in Nepal.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
        <MainLayout>
          <Header />
          <main >{children}</main>
          <Footer />
          <ToastContainer />
        </MainLayout>
      </AppProvider>
      </body>
    </html>
  );
}
